=== bmatsuo/xml-resume/schema/resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://bmats.co/xml-resume/v0"
           targetNamespace="http://bmats.co/xml-resume/v0"
           version="0.1 (20131013)"
           elementFormDefault="qualified">
    <xs:element name="resume" type="Resume"/>
    
    <xs:complexType name="Resume">
        <xs:sequence>
            <xs:element name="header" type="Header"/>
            <xs:element name="objective" type="TextBody"/>
            <xs:element name="skills" type="Skills" maxOccurs="unbounded"/>
            <xs:element name="interests" type="Interests" maxOccurs="unbounded"/>
            <xs:element name="history" type="History"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Header">
        <xs:sequence>
            <xs:element name="name" type="Name"/>
            <xs:element name="contact" type="Contact"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Name">
        <!-- should this be mixed content w/ tagged pieces? -->
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Link">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="href" type="HttpUri"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Contact">
        <xs:sequence>
            <xs:element name="email" type="Email"/>
            <xs:element name="phone" type="Phone" minOccurs="0"/>
            <xs:element name="address" type="Address" minOccurs="0"/>
            <xs:element name="link" type="Link" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Address">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Somewhat modeled after the Portable Contacts specification
                http://portablecontacts.net/draft-spec.html#address_element
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="street" type="xs:token" maxOccurs="unbounded"/>
            <xs:element name="locality" type="xs:token"/>
            <xs:element name="region" type="xs:token"/>
            <xs:element name="postcode" type="xs:token"/>
            <xs:element name="country" type="xs:token" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Skills">
        <xs:sequence>
            <xs:element name="skill" type="Collapsed" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="category" type="xs:token"/>
    </xs:complexType>

    <xs:complexType name="Interests">
        <xs:sequence>
            <xs:element name="interest" type="Collapsed" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="category" type="xs:token"/>
    </xs:complexType>

    <xs:complexType name="History">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="employment" type="Employment"/>
                <xs:element name="academic" type="Academic"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Employment">
        <xs:sequence>
            <xs:element name="position" type="xs:token"/>
            <xs:element name="employer" type="xs:token"/>
            <xs:element name="dates" type="DateRange"/>
            <xs:element name="description" type="TextBody"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DateRange">
        <!-- TODO tighten this down? -->
        <xs:attribute name="from" type="xs:token"/>
        <xs:attribute name="to" type="xs:token"/>
    </xs:complexType>

    <xs:complexType name="Academic">
        <xs:sequence>
            <xs:element name="institution" type="xs:token"/>
            <xs:element name="dates" type="DateRange"/>
            <xs:element name="concentration" type="AcademicConcentration" maxOccurs="unbounded"/>
            <xs:element name="achievement" type="AcademicAchievement" maxOccurs="unbounded"/>
            <xs:element name="description" type="TextBody" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AcademicConcentration">
        <xs:sequence>
            <xs:element name="subject" type="xs:token"/>
            <xs:element name="degree" type="DegreeLevel"/>
        </xs:sequence>
        <xs:attribute name="type" type="MajorMinor"/>
    </xs:complexType>

    <xs:simpleType name="DegreeLevel">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Generally BS, BA, but open to other values.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token"/>
    </xs:simpleType>

    <xs:simpleType name="MajorMinor">
        <xs:restriction base="xs:string">
            <xs:enumeration value="major"/>
            <xs:enumeration value="minor"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AcademicAchievement">
        <xs:sequence>
            <xs:element name="title" type="xs:token"/>
            <xs:element name="subject" type="xs:token" minOccurs="0"/>
            <xs:element name="description" type="Collapsed" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" type="AcademicAchievementType"/>
    </xs:complexType>

    <xs:simpleType name="AcademicAchievementType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="degree"/>
            <xs:enumeration value="award"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TextBody">
        <xs:sequence>
            <xs:element name="para" type="Collapsed" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Collapsed">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Processors MUST ensure strings are collapsed or that excess whitespace is
                otherwise ignored. Not all schema processors will augment instance
                documents in this way.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="HttpUri">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https?://.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="HttpsUri">
        <xs:restriction base="HttpUri">
            <xs:pattern value="https://.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Email">
        <!-- this needs to be relaxed to some degree -->
        <!-- it is tweaked to accept my email address and '+' derivatives  -->
        <xs:restriction base="xs:string">
            <xs:pattern value="\w+([.]\w+)*([+]\w+)?[@]\w+[.]\w{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Phone">
        <!-- hard to restrict -->
        <xs:restriction base="xs:token"/>
    </xs:simpleType>
</xs:schema>

=== bmatsuo/xml-resume/0.2/example/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://bmats.co/xml-resume/0/xsl/html.xsl"?>
<resume xmlns="http://bmats.co/xml-resume/0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://bmats.co/xml-resume/0 http://bmats.co/xml-resume/0/schema/resume.xsd">
    <header>
        <name>Lorem Ipsum Jr</name>
        <contact>
            <email>dolor@sit.amet</email>
            <phone>+1 555 555 5555</phone>
            <address>
                <street>123 consectetur adipiscing elit</street>
                <street>APT 4</street>
                <locality>Phasellus</locality>
                <region>TR</region>
                <postcode>73452</postcode>
                <country>Istique</country>
            </address>
            <link href="https://example.com/convallis">Ante</link>
            <link href="https://example.com/in/sed">Ultricies</link>
        </contact>
    </header>
    <objective>
        <para>
            Molestie id. Fusce est sem, accumsan sed consectetur ut, rhoncus ac
            eros. Etiam in adipiscing massa. Nunc vehicula mi ut risus pretium,
            at pretium nisi sodales.
        </para>
        <para>
            Duis sed magna vel orci tincidunt venenatis. Etiam nec condimentum
            arcu, at auctor nunc. Pellentesque a velit ipsum. Etiam ornare
            aliquam est ut placerat.
        </para>
    </objective>
    <skills category="Aenean">
        <skill>Pellentesque</skill>
        <skill>porttitor</skill>
        <skill>Turpis</skill>
        <skill>Ut</skill>
        <skill>Pretium</skill>
    </skills>
    <skills category="Nam Vel">
        <skill>Neque</skill>
        <skill>Aliquam</skill>
        <skill>Semper Orci</skill>
        <skill>Ac</skill>
        <skill>Ultrices</skill>
        <skill>Erat</skill>
        <skill>Aliquam Rhoncus</skill>
        <skill>Vestibulum</skill>
        <skill>Viverra</skill>
    </skills>
    <interests>
        <interest>Morbi</interest>
        <interest>Vitae dapibus nulla</interest>
        <interest>Vestibulum</interest>
        <interest>Odio quam</interest>
    </interests>
    <history>
        <employment>
            <position>Senior Tempor Non</position>
            <employer>Posuere Vehicula</employer>
            <dates from="Oct 2004" to="Dec 2012"/>
            <description>
                <para>
                    Molestie in ante. Aenean faucibus iaculis libero, ac tempor ipsum
                    volutpat non. Fusce lacinia, diam sed ornare volutpat, massa nunc
                    imperdiet lectus, nec rhoncus turpis turpis non enim. Etiam
                    imperdiet, nibh blandit fermentum imperdiet, tortor tortor
                    tristique justo, et ullamcorper odio quam eget neque.  Integer
                    consectetur urna quis est rutrum varius.
                </para>
            </description>
        </employment>
        <employment>
            <position>Cras Felis Orci</position>
            <employer>Posuere Vel Justo</employer>
            <dates from="Sept 2000" to="Aug 2004"/>
            <description>
                <para>
                    A, accumsan ultrices dolor. Suspendisse hendrerit ipsum vel lectus
                    ultricies, quis blandit neque blandit. Vestibulum ante ipsum
                    primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                </para>
                <para>
                    Fusce purus dui, dapibus non libero mollis, cursus rutrum lectus.
                    Fusce volutpat at odio at interdum. Donec in ante sapien.
                </para>
            </description>
        </employment>
        <academic>
            <institution>Nam quis urna ut sapien</institution>
            <dates from="Aug 1994" to="May 1999"/>
            <concentration type="major">
                <subject>Aretium Laoreet</subject>
                <degree>I.S.</degree>
            </concentration>
            <concentration type="minor">
                <subject>Amet Fermentum</subject>
                <degree/>
            </concentration>
            <achievement>
                <title>Etiam nulla sapien</title>
            </achievement>
        </academic>
    </history>
</resume>

=== bmatsuo/xml-resume/0.1/example/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://bmats.co/xml-resume/0/xsl/html.xsl"?>
<resume xmlns="http://bmats.co/xml-resume/0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://bmats.co/xml-resume/0 http://bmats.co/xml-resume/0/schema/resume.xsd">
    <header>
        <name>Trevor Philips</name>
        <contact>
            <email>t.revor@lifeinvader.com</email>
            <address>
                <street>1218 Palmas Blvd</street>
                <street>APT 4</street>
                <locality>Vespucci Beach</locality>
                <region>CA</region>
                <postcode>73452</postcode>
                <country>USA</country>
            </address>
            <link href="https://example.com/lifeinvader">Life Invader</link>
            <link href="https://linkedin.com/in/trevorphilps">LinkedIn</link>
        </contact>
    </header>
    <objective>
        <para>
            I want to make money. I don't care what I have to do.
        </para>
        <para>
            Danger. Distruction. Maybe someones Death. Fuck it.
            Just show me the money.
        </para>
    </objective>
    <skills>
        <skill>Firearms</skill>
        <skill>Explosives</skill>
        <skill>Planes</skill>
        <skill>Helicopters</skill>
    </skills>
    <interests>
        <interest>Money</interest>
        <interest>Drugs</interest>
        <interest>Alcohol</interest>
        <interest>Deviancy</interest>
    </interests>
    <history>
        <employment>
            <position>Gun Man</position>
            <employer>Self employed</employer>
            <dates from="Oct 2013" to="Oct 2013"/>
            <description>
                <para>
                </para>
            </description>
        </employment>
        <employment>
            <position></position>
            <employer>Federal Investigation Bureau</employer>
            <dates from="Oct 2013" to="Oct 2013"/>
            <description>
                <para>
                </para>
            </description>
        </employment>
        <academic>
            <institution>Los Santos Halfway House and Night School</institution>
            <dates from="Sep 1998" to="Mar 2010"/>
            <concentration type="major">
                <subject>School</subject>
                <degree>G.E.D.</degree>
            </concentration>
            <achievement>
                <title>Most likely to deal heroin again in the future</title>
            </achievement>
        </academic>
    </history>
</resume>

=== bmatsuo/xml-resume/example/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://bmats.co/xml-resume/0/xsl/html.xsl"?>
<resume xmlns="http://bmats.co/xml-resume/0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://bmats.co/xml-resume/0 http://bmats.co/xml-resume/0/schema/resume.xsd">
    <header>
        <name>Trevor Philips</name>
        <contact>
            <email>t.revor@lifeinvader.com</email>
            <phone>+1 555 555 5555</phone>
            <address>
                <street>1218 Palmas Blvd</street>
                <street>APT 4</street>
                <locality>Vespucci Beach</locality>
                <region>CA</region>
                <postcode>73452</postcode>
                <country>USA</country>
            </address>
            <link href="https://example.com/lifeinvader">Life Invader</link>
            <link href="https://linkedin.com/in/trevorphilps">LinkedIn</link>
        </contact>
    </header>
    <objective>
        <para>
            I want to make money. I don't care what I have to do.
        </para>
        <para>
            Danger. Destruction. Maybe someones Death. Fuck it.
            Just show me the money.
        </para>
    </objective>
    <skills category="things">
        <skill>Firearms</skill>
        <skill>Explosives</skill>
        <skill>Planes</skill>
        <skill>Helicopters</skill>
    </skills>
    <skills category="other things">
        <skill>Phalandering</skill>
    </skills>
    <interests>
        <interest>Money</interest>
        <interest>Drugs</interest>
        <interest>Alcohol</interest>
        <interest>Deviancy</interest>
    </interests>
    <history>
        <employment>
            <position>Gun Man</position>
            <employer>Self employed</employer>
            <dates from="Oct 2013" to="Oct 2013"/>
            <description>
                <para>
                    I shot some shit.
                </para>
            </description>
        </employment>
        <employment>
            <position>Gopher</position>
            <employer>Federal Investigation Bureau</employer>
            <dates from="Oct 2013" to="Oct 2013"/>
            <description>
                <para>
                    I did some fucked up shit for those assholes.
                </para>
                <para>
                    To top it off I never got paid a fucking dime.
                </para>
            </description>
        </employment>
        <academic>
            <institution>Los Santos Halfway House and Night School</institution>
            <dates from="Sep 1998" to="Mar 2010"/>
            <concentration type="major">
                <subject>School</subject>
                <degree>G.E.D.</degree>
            </concentration>
            <achievement>
                <title>Most likely to deal heroin again in the future</title>
            </achievement>
        </academic>
    </history>
</resume>
